<?php $parties = [
    '50 PLUS' => [
        'Stelling 1' => 'Eens',
        'Stelling 2' => 'Oneens',
        'Stelling 3' => 'Eens',
        'Stelling 4' => 'Oneens',
        'Stelling 5' => 'Eens',
        'Stelling 6' => 'Eens',
        'Stelling 7' => 'Eens',
        'Stelling 8' => 'Eens',
        'Stelling 9' => 'Oneens',
        'Stelling 10' => 'Oneens',
        'Stelling 11' => 'Oneens',
        'Stelling 12' => 'Eens',
        'Stelling 13' => 'Eens',
        'Stelling 14' => 'Oneens',
        'Stelling 15' => 'Oneens',
         
    ],
    'BBB' => [
        'Stelling 1' => 'Oneens',
        'Stelling 2' => 'Eens',
        'Stelling 3' => 'Oneens',
        'Stelling 4' => 'Oneens',
        'Stelling 5' => 'Oneens',
        'Stelling 6' => 'Eens',
        'Stelling 7' => 'Oneens',
        'Stelling 8' => 'Oneens',
        'Stelling 9' => 'Eens',
        'Stelling 10' => 'Oneens',
        'Stelling 11' => 'Eens',
        'Stelling 12' => 'Eens',
        'Stelling 13' => 'Oneens',
        'Stelling 14' => 'Oneens',
        'Stelling 15' => 'Oneens',
         
    ],
     'VNL' => [
        'Stelling 1' => 'Oneens',
        'Stelling 2' => 'Eens',
        'Stelling 3' => 'Oneens',
        'Stelling 4' => 'Oneens',
        'Stelling 5' => 'Oneens',
        'Stelling 6' => 'Eens',
        'Stelling 7' => 'Oneens',
        'Stelling 8' => 'Oneens',
        'Stelling 9' => 'Eens',
        'Stelling 10' => 'Oneens',
        'Stelling 11' => 'Eens',
        'Stelling 12' => 'Oneens',
        'Stelling 13' => 'Oneens',
        'Stelling 14' => 'Oneens',
        'Stelling 15' => 'Oneens',
         
    ],
    'CDA' => [
        'Stelling 1' => 'Eens',
        'Stelling 2' => 'Oneens',
        'Stelling 3' => 'Eens',
        'Stelling 4' => 'Oneens',
        'Stelling 5' => 'Eens',
        'Stelling 6' => 'Eens',
        'Stelling 7' => 'Oneens',
        'Stelling 8' => 'Eens',
        'Stelling 9' => 'Eens',
        'Stelling 10' => 'Eens',
        'Stelling 11' => 'Eens',
        'Stelling 12' => 'Eens',
        'Stelling 13' => 'Eens',
        'Stelling 14' => 'Oneens',
        'Stelling 15' => 'Oneens',
         
    ],
     'CU' => [
        'Stelling 1' => 'Eens',
        'Stelling 2' => 'Oneens',
        'Stelling 3' => 'Eens',
        'Stelling 4' => 'Oneens',
        'Stelling 5' => 'Eens',
        'Stelling 6' => 'Geen Mening',
        'Stelling 7' => 'Oneens',
        'Stelling 8' => 'Oneens',
        'Stelling 9' => 'Geen Mening',
        'Stelling 10' => 'Oneens',
        'Stelling 11' => 'Oneens',
        'Stelling 12' => 'Oneens',
        'Stelling 13' => 'Eens',
        'Stelling 14' => 'Oneens',
        'Stelling 15' => 'Oneens',
         
    ],
    'D66' => [
        'Stelling 1' => 'Eens',
        'Stelling 2' => 'Oneens',
        'Stelling 3' => 'Eens',
        'Stelling 4' => 'Eens',
        'Stelling 5' => 'Eens',
        'Stelling 6' => 'Eens',
        'Stelling 7' => 'Oneens',
        'Stelling 8' => 'Eens',
        'Stelling 9' => 'Eens',
        'Stelling 10' => 'Eens',
        'Stelling 11' => 'Oneens',
        'Stelling 12' => 'Eens',
        'Stelling 13' => 'Eens',
        'Stelling 14' => 'Geen Mening',
        'Stelling 15' => 'Geen Mening',
         
    ],
     'PvdD' => [
        'Stelling 1' => 'Eens',
        'Stelling 2' => 'Oneens',
        'Stelling 3' => 'Eens',
        'Stelling 4' => 'Eens',
        'Stelling 5' => 'Eens',
        'Stelling 6' => 'Oneens',
        'Stelling 7' => 'Eens',
        'Stelling 8' => 'Eens',
        'Stelling 9' => 'Oneens',
        'Stelling 10' => 'Eens',
        'Stelling 11' => 'Oneens',
        'Stelling 12' => 'Oneens',
        'Stelling 13' => 'Eens',
        'Stelling 14' => 'Oneens',
        'Stelling 15' => 'Eens',
         
    ],
    'JA21' => [
        'Stelling 1' => 'Oneens',
        'Stelling 2' => 'Eens',
        'Stelling 3' => 'Oneens',
        'Stelling 4' => 'Oneens',
        'Stelling 5' => 'Oneens',
        'Stelling 6' => 'Eens',
        'Stelling 7' => 'Oneens',
        'Stelling 8' => 'Eens',
        'Stelling 9' => 'Eens',
        'Stelling 10' => 'Oneens',
        'Stelling 11' => 'Eens',
        'Stelling 12' => 'Eens',
        'Stelling 13' => 'Oneens',
        'Stelling 14' => 'Oneens',
        'Stelling 15' => 'Oneens',
         
    ],
     'MDD' => [
        'Stelling 1' => 'Oneens',
        'Stelling 2' => 'Eens',
        'Stelling 3' => 'Eens',
        'Stelling 4' => 'Oneens',
        'Stelling 5' => 'Oneens',
        'Stelling 6' => 'Eens',
        'Stelling 7' => 'Oneens',
        'Stelling 8' => 'Eens',
        'Stelling 9' => 'Eens',
        'Stelling 10' => 'Geen Mening',
        'Stelling 11' => 'Eens',
        'Stelling 12' => 'Oneens',
        'Stelling 13' => 'Oneens',
        'Stelling 14' => 'Oneens',
        'Stelling 15' => 'Oneens',
         
    ],
    'NLPLAN' => [
        'Stelling 1' => 'Eens',
        'Stelling 2' => 'Oneens',
        'Stelling 3' => 'Eens',
        'Stelling 4' => 'Eens',
        'Stelling 5' => 'Eens',
        'Stelling 6' => 'Eens',
        'Stelling 7' => 'Oneens',
        'Stelling 8' => 'Eens',
        'Stelling 9' => 'Eens',
        'Stelling 10' => 'Eens',
        'Stelling 11' => 'Eens',
        'Stelling 12' => 'Oneens',
        'Stelling 13' => 'Oneens',
        'Stelling 14' => 'Eens',
        'Stelling 15' => 'Oneens',
         
    ],
     'NSC' => [
        'Stelling 1' => 'Eens',
        'Stelling 2' => 'Oneens',
        'Stelling 3' => 'Eens',
        'Stelling 4' => 'Oneens',
        'Stelling 5' => 'Eens',
        'Stelling 6' => 'Eens',
        'Stelling 7' => 'Eens',
        'Stelling 8' => 'Oneens',
        'Stelling 9' => 'Eens',
        'Stelling 10' => 'Oneens',
        'Stelling 11' => 'Eens',
        'Stelling 12' => 'Eens',
        'Stelling 13' => 'Eens',
        'Stelling 14' => 'Oneens',
        'Stelling 15' => 'Oneens',
         
    ],
    'PPNL' => [
        'Stelling 1' => 'Eens',
        'Stelling 2' => 'Oneens',
        'Stelling 3' => 'Eens',
        'Stelling 4' => 'Eens',
        'Stelling 5' => 'Eens',
        'Stelling 6' => 'Oneens',
        'Stelling 7' => 'Eens',
        'Stelling 8' => 'Eens',
        'Stelling 9' => 'Oneens',
        'Stelling 10' => 'Eens',
        'Stelling 11' => 'Eens',
        'Stelling 12' => 'Oneens',
        'Stelling 13' => 'Eens',
        'Stelling 14' => 'Oneens',
        'Stelling 15' => 'Eens',
         
    ],
     'PVDA' => [
        'Stelling 1' => 'Eens',
        'Stelling 2' => 'Oneens',
        'Stelling 3' => 'Eens',
        'Stelling 4' => 'Oneens',
        'Stelling 5' => 'Eens',
        'Stelling 6' => 'Oneens',
        'Stelling 7' => 'Eens',
        'Stelling 8' => 'Eens',
        'Stelling 9' => 'Oneens',
        'Stelling 10' => 'Eens',
        'Stelling 11' => 'Oneens',
        'Stelling 12' => 'Oneens',
        'Stelling 13' => 'Eens',
        'Stelling 14' => 'Eens',
        'Stelling 15' => 'Geen Mening',
         
    ],
    'SGP' => [
        'Stelling 1' => 'Oneens',
        'Stelling 2' => 'Oneens',
        'Stelling 3' => 'Eens',
        'Stelling 4' => 'Oneens',
        'Stelling 5' => 'Eens',
        'Stelling 6' => 'Eens',
        'Stelling 7' => 'Oneens',
        'Stelling 8' => 'Oneens',
        'Stelling 9' => 'Eens',
        'Stelling 10' => 'Oneens',
        'Stelling 11' => 'Eens',
        'Stelling 12' => 'Oneens',
        'Stelling 13' => 'Eens',
        'Stelling 14' => 'Oneens',
        'Stelling 15' => 'Oneens',
         
    ],
     'SP' => [
        'Stelling 1' => 'Eens',
        'Stelling 2' => 'Oneens',
        'Stelling 3' => 'Eens',
        'Stelling 4' => 'Oneens',
        'Stelling 5' => 'Eens',
        'Stelling 6' => 'Oneens',
        'Stelling 7' => 'Eens',
        'Stelling 8' => 'Eens',
        'Stelling 9' => 'Oneens',
        'Stelling 10' => 'Eens',
        'Stelling 11' => 'Eens',
        'Stelling 12' => 'Oneens',
        'Stelling 13' => 'Oneens',
        'Stelling 14' => 'Oneens',
        'Stelling 15' => 'Eens',
         
    ],
    'FVD' => [
        'Stelling 1' => 'Oneens',
       'Stelling 2' => 'Eens',
        'Stelling 3' => 'Oneens',
        'Stelling 4' => 'Oneens',
        'Stelling 5' => 'Oneens',
        'Stelling 6' => 'Eens',
        'Stelling 7' => 'Oneens',
        'Stelling 8' => 'Oneens',
        'Stelling 9' => 'Oneens',
        'Stelling 10' => 'Oneens',
        'Stelling 11' => 'Eens',
        'Stelling 12' => 'Eens',
        'Stelling 13' => 'Oneens',
        'Stelling 14' => 'Oneens',
        'Stelling 15' => 'Oneens',
         
    ],
     'VDR' => [
        'Stelling 1' => 'Eens',
        'Stelling 2' => 'Eens',
        'Stelling 3' => 'Eens',
        'Stelling 4' => 'Eens',
        'Stelling 5' => 'Eens',
        'Stelling 6' => 'Eens',
        'Stelling 7' => 'Eens',
        'Stelling 8' => 'Eens',
        'Stelling 9' => 'Oneens',
        'Stelling 10' => 'Eens',
        'Stelling 11' => 'Eens',
        'Stelling 12' => 'Oneens',
        'Stelling 13' => 'Eens',
        'Stelling 14' => 'Eens',
        'Stelling 15' => 'Geen Mening',
         
    ],
    'PVV' => [
        'Stelling 1' => 'Oneens',
        'Stelling 2' => 'Eens',
        'Stelling 3' => 'Eens',
        'Stelling 4' => 'Oneens',
        'Stelling 5' => 'Oneens',
        'Stelling 6' => 'Eens',
        'Stelling 7' => 'Oneens',
        'Stelling 8' => 'Eens',
        'Stelling 9' => 'Eens',
        'Stelling 10' => 'Oneens',
        'Stelling 11' => 'Eens',
        'Stelling 12' => 'Eens',
        'Stelling 13' => 'Oneens',
        'Stelling 14' => 'Oneens',
        'Stelling 15' => 'Oneens',
         
    ],
     'VOLT' => [
        'Stelling 1' => 'Eens',
        'Stelling 2' => 'Oneens',
        'Stelling 3' => 'Eens',
        'Stelling 4' => 'Eens',
        'Stelling 5' => 'Eens',
        'Stelling 6' => 'Oneens',
        'Stelling 7' => 'Eens',
        'Stelling 8' => 'Eens',
        'Stelling 9' => 'Eens',
        'Stelling 10' => 'Eens',
        'Stelling 11' => 'Oneens',
        'Stelling 12' => 'Eens',
        'Stelling 13' => 'Eens',
        'Stelling 14' => 'Eens',
        'Stelling 15' => 'Geen Mening',
         
    ],
    'VVD' => [
        'Stelling 1' => 'Eens',
        'Stelling 2' => 'Oneens',
        'Stelling 3' => 'Eens',
        'Stelling 4' => 'Oneens',
        'Stelling 5' => 'Eens',
        'Stelling 6' => 'Eens',
        'Stelling 7' => 'Oneens',
        'Stelling 8' => 'Oneens',
        'Stelling 9' => 'Eens',
        'Stelling 10' => 'Eens',
        'Stelling 11' => 'Eens',
        'Stelling 12' => 'Eens',
        'Stelling 13' => 'Eens',
        'Stelling 14' => 'Eens',
        'Stelling 15' => 'Oneens',
         
    ],
]; ?>

