<?php $partijen = [
    '50 PLUS' => [
        'Evenredige verdeling asielzoeker' => 'Eens',
        'Nepnieuws' => 'Oneens',
        'Minimumbelasting bedrijven' => 'Eens',
        'Stemgerechtigde leeftijd' => 'Oneens',
        'Prijs CO2-uitstoot' => 'Eens',
        'Asielzoekers en ontwikkelingshul' => 'Eens',
        'Gezichtsherkenning politie' => 'Eens',
        'Recht van initiatief' => 'Eens',
        'Meer kernenergie' => 'Oneens',
        'LHBTIQ+-rechten' => 'Oneens',
        'Europa van meerdere snelheden' => 'Oneens',
        'Genetische modificatie' => 'Eens',
        'Verplichte vliegbelasting' => 'Eens',
        'Digitale Euro' => 'Oneens',
        'Samenwerking Israël' => 'Oneens',
         
    ],
    'BBB' => [
        'Evenredige verdeling asielzoeker' => 'Oneens',
        'Nepnieuws' => 'Eens',
        'Minimumbelasting bedrijven' => 'Oneens',
        'Stemgerechtigde leeftijd' => 'Oneens',
        'Prijs CO2-uitstoot' => 'Oneens',
        'Asielzoekers en ontwikkelingshul' => 'Eens',
        'Gezichtsherkenning politie' => 'Oneens',
        'Recht van initiatief' => 'Oneens',
        'Meer kernenergie' => 'Eens',
        'LHBTIQ+-rechten' => 'Oneens',
        'Europa van meerdere snelheden' => 'Eens',
        'Genetische modificatie' => 'Eens',
        'Verplichte vliegbelasting' => 'Oneens',
        'Digitale Euro' => 'Oneens',
        'Samenwerking Israël' => 'Oneens',
         
    ],
     'VNL' => [
        'Evenredige verdeling asielzoeker' => 'Oneens',
        'Nepnieuws' => 'Eens',
        'Minimumbelasting bedrijven' => 'Oneens',
        'Stemgerechtigde leeftijd' => 'Oneens',
        'Prijs CO2-uitstoot' => 'Oneens',
        'Asielzoekers en ontwikkelingshul' => 'Eens',
        'Gezichtsherkenning politie' => 'Oneens',
        'Recht van initiatief' => 'Oneens',
        'Meer kernenergie' => 'Eens',
        'LHBTIQ+-rechten' => 'Oneens',
        'Europa van meerdere snelheden' => 'Eens',
        'Genetische modificatie' => 'Oneens',
        'Verplichte vliegbelasting' => 'Oneens',
        'Digitale Euro' => 'Oneens',
        'Samenwerking Israël' => 'Oneens',
         
    ],
    'CDA' => [
        'Evenredige verdeling asielzoeker' => 'Eens',
        'Nepnieuws' => 'Oneens',
        'Minimumbelasting bedrijven' => 'Eens',
        'Stemgerechtigde leeftijd' => 'Oneens',
        'Prijs CO2-uitstoot' => 'Eens',
        'Asielzoekers en ontwikkelingshul' => 'Eens',
        'Gezichtsherkenning politie' => 'Oneens',
        'Recht van initiatief' => 'Eens',
        'Meer kernenergie' => 'Eens',
        'LHBTIQ+-rechten' => 'Eens',
        'Europa van meerdere snelheden' => 'Eens',
        'Genetische modificatie' => 'Eens',
        'Verplichte vliegbelasting' => 'Eens',
        'Digitale Euro' => 'Oneens',
        'Samenwerking Israël' => 'Oneens',
         
    ],
     'CU' => [
        'Evenredige verdeling asielzoeker' => 'Eens',
        'Nepnieuws' => 'Oneens',
        'Minimumbelasting bedrijven' => 'Eens',
        'Stemgerechtigde leeftijd' => 'Oneens',
        'Prijs CO2-uitstoot' => 'Eens',
        'Asielzoekers en ontwikkelingshul' => 'Geen Mening',
        'Gezichtsherkenning politie' => 'Oneens',
        'Recht van initiatief' => 'Oneens',
        'Meer kernenergie' => 'Geen Mening',
        'LHBTIQ+-rechten' => 'Oneens',
        'Europa van meerdere snelheden' => 'Oneens',
        'Genetische modificatie' => 'Oneens',
        'Verplichte vliegbelasting' => 'Eens',
        'Digitale Euro' => 'Oneens',
        'Samenwerking Israël' => 'Oneens',
         
    ],
    'D66' => [
        'Evenredige verdeling asielzoeker' => 'Eens',
        'Nepnieuws' => 'Oneens',
        'Minimumbelasting bedrijven' => 'Eens',
        'Stemgerechtigde leeftijd' => 'Eens',
        'Prijs CO2-uitstoot' => 'Eens',
        'Asielzoekers en ontwikkelingshul' => 'Eens',
        'Gezichtsherkenning politie' => 'Oneens',
        'Recht van initiatief' => 'Eens',
        'Meer kernenergie' => 'Eens',
        'LHBTIQ+-rechten' => 'Eens',
        'Europa van meerdere snelheden' => 'Oneens',
        'Genetische modificatie' => 'Eens',
        'Verplichte vliegbelasting' => 'Eens',
        'Digitale Euro' => 'Geen Mening',
        'Samenwerking Israël' => 'Geen Mening',
         
    ],
     'PvdD' => [
        'Evenredige verdeling asielzoeker' => 'Eens',
        'Nepnieuws' => 'Oneens',
        'Minimumbelasting bedrijven' => 'Eens',
        'Stemgerechtigde leeftijd' => 'Eens',
        'Prijs CO2-uitstoot' => 'Eens',
        'Asielzoekers en ontwikkelingshul' => 'Oneens',
        'Gezichtsherkenning politie' => 'Eens',
        'Recht van initiatief' => 'Eens',
        'Meer kernenergie' => 'Oneens',
        'LHBTIQ+-rechten' => 'Eens',
        'Europa van meerdere snelheden' => 'Oneens',
        'Genetische modificatie' => 'Oneens',
        'Verplichte vliegbelasting' => 'Eens',
        'Digitale Euro' => 'Oneens',
        'Samenwerking Israël' => 'Eens',
         
    ],
    'JA21' => [
        'Evenredige verdeling asielzoeker' => 'Oneens',
        'Nepnieuws' => 'Eens',
        'Minimumbelasting bedrijven' => 'Oneens',
        'Stemgerechtigde leeftijd' => 'Oneens',
        'Prijs CO2-uitstoot' => 'Oneens',
        'Asielzoekers en ontwikkelingshul' => 'Eens',
        'Gezichtsherkenning politie' => 'Oneens',
        'Recht van initiatief' => 'Eens',
        'Meer kernenergie' => 'Eens',
        'LHBTIQ+-rechten' => 'Oneens',
        'Europa van meerdere snelheden' => 'Eens',
        'Genetische modificatie' => 'Eens',
        'Verplichte vliegbelasting' => 'Oneens',
        'Digitale Euro' => 'Oneens',
        'Samenwerking Israël' => 'Oneens',
         
    ],
     'MDD' => [
        'Evenredige verdeling asielzoeker' => 'Oneens',
        'Nepnieuws' => 'Eens',
        'Minimumbelasting bedrijven' => 'Eens',
        'Stemgerechtigde leeftijd' => 'Oneens',
        'Prijs CO2-uitstoot' => 'Oneens',
        'Asielzoekers en ontwikkelingshul' => 'Eens',
        'Gezichtsherkenning politie' => 'Oneens',
        'Recht van initiatief' => 'Eens',
        'Meer kernenergie' => 'Eens',
        'LHBTIQ+-rechten' => 'Geen Mening',
        'Europa van meerdere snelheden' => 'Eens',
        'Genetische modificatie' => 'Oneens',
        'Verplichte vliegbelasting' => 'Oneens',
        'Digitale Euro' => 'Oneens',
        'Samenwerking Israël' => 'Oneens',
         
    ],
    'NLPLAN' => [
        'Evenredige verdeling asielzoeker' => 'Eens',
        'Nepnieuws' => 'Oneens',
        'Minimumbelasting bedrijven' => 'Eens',
        'Stemgerechtigde leeftijd' => 'Eens',
        'Prijs CO2-uitstoot' => 'Eens',
        'Asielzoekers en ontwikkelingshul' => 'Eens',
        'Gezichtsherkenning politie' => 'Oneens',
        'Recht van initiatief' => 'Eens',
        'Meer kernenergie' => 'Eens',
        'LHBTIQ+-rechten' => 'Eens',
        'Europa van meerdere snelheden' => 'Eens',
        'Genetische modificatie' => 'Oneens',
        'Verplichte vliegbelasting' => 'Oneens',
        'Digitale Euro' => 'Eens',
        'Samenwerking Israël' => 'Oneens',
         
    ],
     'NSC' => [
        'Evenredige verdeling asielzoeker' => 'Eens',
        'Nepnieuws' => 'Oneens',
        'Minimumbelasting bedrijven' => 'Eens',
        'Stemgerechtigde leeftijd' => 'Oneens',
        'Prijs CO2-uitstoot' => 'Eens',
        'Asielzoekers en ontwikkelingshul' => 'Eens',
        'Gezichtsherkenning politie' => 'Eens',
        'Recht van initiatief' => 'Oneens',
        'Meer kernenergie' => 'Eens',
        'LHBTIQ+-rechten' => 'Oneens',
        'Europa van meerdere snelheden' => 'Eens',
        'Genetische modificatie' => 'Eens',
        'Verplichte vliegbelasting' => 'Eens',
        'Digitale Euro' => 'Oneens',
        'Samenwerking Israël' => 'Oneens',
         
    ],
    'PPNL' => [
        'Evenredige verdeling asielzoeker' => 'Eens',
        'Nepnieuws' => 'Oneens',
        'Minimumbelasting bedrijven' => 'Eens',
        'Stemgerechtigde leeftijd' => 'Eens',
        'Prijs CO2-uitstoot' => 'Eens',
        'Asielzoekers en ontwikkelingshul' => 'Oneens',
        'Gezichtsherkenning politie' => 'Eens',
        'Recht van initiatief' => 'Eens',
        'Meer kernenergie' => 'Oneens',
        'LHBTIQ+-rechten' => 'Eens',
        'Europa van meerdere snelheden' => 'Eens',
        'Genetische modificatie' => 'Oneens',
        'Verplichte vliegbelasting' => 'Eens',
        'Digitale Euro' => 'Oneens',
        'Samenwerking Israël' => 'Eens',
         
    ],
     'PVDA' => [
        'Evenredige verdeling asielzoeker' => 'Eens',
        'Nepnieuws' => 'Oneens',
        'Minimumbelasting bedrijven' => 'Eens',
        'Stemgerechtigde leeftijd' => 'Oneens',
        'Prijs CO2-uitstoot' => 'Eens',
        'Asielzoekers en ontwikkelingshul' => 'Oneens',
        'Gezichtsherkenning politie' => 'Eens',
        'Recht van initiatief' => 'Eens',
        'Meer kernenergie' => 'Oneens',
        'LHBTIQ+-rechten' => 'Eens',
        'Europa van meerdere snelheden' => 'Oneens',
        'Genetische modificatie' => 'Oneens',
        'Verplichte vliegbelasting' => 'Eens',
        'Digitale Euro' => 'Eens',
        'Samenwerking Israël' => 'Geen Mening',
         
    ],
    'SGP' => [
        'Evenredige verdeling asielzoeker' => 'Oneens',
        'Nepnieuws' => 'Oneens',
        'Minimumbelasting bedrijven' => 'Eens',
        'Stemgerechtigde leeftijd' => 'Oneens',
        'Prijs CO2-uitstoot' => 'Eens',
        'Asielzoekers en ontwikkelingshul' => 'Eens',
        'Gezichtsherkenning politie' => 'Oneens',
        'Recht van initiatief' => 'Oneens',
        'Meer kernenergie' => 'Eens',
        'LHBTIQ+-rechten' => 'Oneens',
        'Europa van meerdere snelheden' => 'Eens',
        'Genetische modificatie' => 'Oneens',
        'Verplichte vliegbelasting' => 'Eens',
        'Digitale Euro' => 'Oneens',
        'Samenwerking Israël' => 'Oneens',
         
    ],
     'SP' => [
        'Evenredige verdeling asielzoeker' => 'Eens',
        'Nepnieuws' => 'Oneens',
        'Minimumbelasting bedrijven' => 'Eens',
        'Stemgerechtigde leeftijd' => 'Oneens',
        'Prijs CO2-uitstoot' => 'Eens',
        'Asielzoekers en ontwikkelingshul' => 'Oneens',
        'Gezichtsherkenning politie' => 'Eens',
        'Recht van initiatief' => 'Eens',
        'Meer kernenergie' => 'Oneens',
        'LHBTIQ+-rechten' => 'Eens',
        'Europa van meerdere snelheden' => 'Eens',
        'Genetische modificatie' => 'Oneens',
        'Verplichte vliegbelasting' => 'Oneens',
        'Digitale Euro' => 'Oneens',
        'Samenwerking Israël' => 'Eens',
         
    ],
    'FVD' => [
        'Evenredige verdeling asielzoeker' => 'Oneens',
       'Nepnieuws' => 'Eens',
        'Minimumbelasting bedrijven' => 'Oneens',
        'Stemgerechtigde leeftijd' => 'Oneens',
        'Prijs CO2-uitstoot' => 'Oneens',
        'Asielzoekers en ontwikkelingshul' => 'Eens',
        'Gezichtsherkenning politie' => 'Oneens',
        'Recht van initiatief' => 'Oneens',
        'Meer kernenergie' => 'Oneens',
        'LHBTIQ+-rechten' => 'Oneens',
        'Europa van meerdere snelheden' => 'Eens',
        'Genetische modificatie' => 'Eens',
        'Verplichte vliegbelasting' => 'Oneens',
        'Digitale Euro' => 'Oneens',
        'Samenwerking Israël' => 'Oneens',
         
    ],
     'VDR' => [
        'Evenredige verdeling asielzoeker' => 'Eens',
        'Nepnieuws' => 'Eens',
        'Minimumbelasting bedrijven' => 'Eens',
        'Stemgerechtigde leeftijd' => 'Eens',
        'Prijs CO2-uitstoot' => 'Eens',
        'Asielzoekers en ontwikkelingshul' => 'Eens',
        'Gezichtsherkenning politie' => 'Eens',
        'Recht van initiatief' => 'Eens',
        'Meer kernenergie' => 'Oneens',
        'LHBTIQ+-rechten' => 'Eens',
        'Europa van meerdere snelheden' => 'Eens',
        'Genetische modificatie' => 'Oneens',
        'Verplichte vliegbelasting' => 'Eens',
        'Digitale Euro' => 'Eens',
        'Samenwerking Israël' => 'Geen Mening',
         
    ],
    'PVV' => [
        'Evenredige verdeling asielzoeker' => 'Oneens',
        'Nepnieuws' => 'Eens',
        'Minimumbelasting bedrijven' => 'Eens',
        'Stemgerechtigde leeftijd' => 'Oneens',
        'Prijs CO2-uitstoot' => 'Oneens',
        'Asielzoekers en ontwikkelingshul' => 'Eens',
        'Gezichtsherkenning politie' => 'Oneens',
        'Recht van initiatief' => 'Eens',
        'Meer kernenergie' => 'Eens',
        'LHBTIQ+-rechten' => 'Oneens',
        'Europa van meerdere snelheden' => 'Eens',
        'Genetische modificatie' => 'Eens',
        'Verplichte vliegbelasting' => 'Oneens',
        'Digitale Euro' => 'Oneens',
        'Samenwerking Israël' => 'Oneens',
         
    ],
     'VOLT' => [
        'Evenredige verdeling asielzoeker' => 'Eens',
        'Nepnieuws' => 'Oneens',
        'Minimumbelasting bedrijven' => 'Eens',
        'Stemgerechtigde leeftijd' => 'Eens',
        'Prijs CO2-uitstoot' => 'Eens',
        'Asielzoekers en ontwikkelingshul' => 'Oneens',
        'Gezichtsherkenning politie' => 'Eens',
        'Recht van initiatief' => 'Eens',
        'Meer kernenergie' => 'Eens',
        'LHBTIQ+-rechten' => 'Eens',
        'Europa van meerdere snelheden' => 'Oneens',
        'Genetische modificatie' => 'Eens',
        'Verplichte vliegbelasting' => 'Eens',
        'Digitale Euro' => 'Eens',
        'Samenwerking Israël' => 'Geen Mening',
         
    ],
    'VVD' => [
        'Evenredige verdeling asielzoeker' => 'Eens',
        'Nepnieuws' => 'Oneens',
        'Minimumbelasting bedrijven' => 'Eens',
        'Stemgerechtigde leeftijd' => 'Oneens',
        'Prijs CO2-uitstoot' => 'Eens',
        'Asielzoekers en ontwikkelingshul' => 'Eens',
        'Gezichtsherkenning politie' => 'Oneens',
        'Recht van initiatief' => 'Oneens',
        'Meer kernenergie' => 'Eens',
        'LHBTIQ+-rechten' => 'Eens',
        'Europa van meerdere snelheden' => 'Eens',
        'Genetische modificatie' => 'Eens',
        'Verplichte vliegbelasting' => 'Eens',
        'Digitale Euro' => 'Eens',
        'Samenwerking Israël' => 'Oneens',
         
    ],
]; ?>

